### ISSUE TITLE
Failure to parse a long element

### ISSUE THREAD

**Issue by johnwhitington** [ncannasse/xml-light#1] opened 2014-09-08 10:27 UTC
The attached piece of XML, which I have no reason to suspect is not valid, will not parse in xml-light, with an error at line 26 (the very long xapGImg:image tag). Am I doing something wrong?

Oh, here's the file: http://www.coherentpdf.com/foo.xml

**Comment by merciChef** [comment] 2016-12-09 17:46
I'm experiencing similar issues. I think the problem is the HTML entities like **&amp;#xA;** in your file.

I tested using Xml.to_string (Xml.parse_string some_string). The parsing fails if some_string contains **"&amp;#xA;"** or  **"&amp;#x00E8;"** but succeeds with **"&amp;#232;"** or **"&amp;egrave;"**.
Moreover, Xml.to_string (Xml.parse_string "&amp;egrave;") returns **"&amp;amp;egrave;"** instead of **"&amp;egrave;"** itself.

Is a XML parser supposed to behave like this ?

**Comment by hhugo** [comment] 2023-02-21 18:15
fixed by https://github.com/ncannasse/xml-light/pull/6

**Closed by hhugo** 2023-02-21 18:15 UTC
